# docker-compose up --build
# docker-compose -p lab4 -f docker-compose.yml up -d --build

version: '3.9'

services:
  mongo-ires:
    image: mongo:latest
    container_name: mongo-lab4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db-data:/data/db
    networks:
      - lab4

volumes:
  mongo-db:
    driver: local
  mongo_data:

networks:
  ires:
    driver: bridge